/**
 * Team Controller for EventNexus Backend
 * Handles team creation, joining, retrieval, and deletion
 * Implements Requirements 7.1-7.6, 8.1-8.6, 9.2
 */

const Team = require('../models/Team');
const Event = require('../models/Event');
const Registration = require('../models/Registration');
const asyncHandler = require('../utils/asyncHandler');
const { NotFoundError, ConflictError } = require('../utils/errors');

/**
 * Create Team
 * POST /api/teams
 * Protected route (admin only)
 * 
 * Validates: Requirements 7.1, 7.2, 7.3, 7.6
 * 
 * Checks:
 * - Admin role (via middleware)
 * - Event exists
 * - Capacity is positive integer (via model validation)
 * 
 * Creates team with generated joinCode
 * Returns created team
 */
exports.createTeam = asyncHandler(async (req, res, next) => {
  const { name, eventId, capacity } = req.body;

  // Verify event exists
  const event = await Event.findById(eventId);
  if (!event) {
    throw new NotFoundError('Event', eventId);
  }

  // Create team (joinCode will be auto-generated by pre-save hook)
  const team = await Team.create({
    name,
    event: eventId,
    capacity,
    createdBy: req.user._id
  });

  // Populate event info for response
  await team.populate('event', 'title date location');
  await team.populate('createdBy', 'email role');

  res.status(201).json({
    success: true,
    team
  });
});

/**
 * Join Team
 * POST /api/teams/join
 * Protected route (participant or admin)
 * 
 * Validates: Requirements 8.1, 8.2, 8.3, 8.4, 8.5
 * 
 * Checks:
 * - Team exists by joinCode
 * - User is registered for the event
 * - Team has available capacity
 * - User is not already in another team for the same event
 * 
 * Adds user to team members
 * Returns updated team
 */
exports.joinTeam = asyncHandler(async (req, res, next) => {
  const { joinCode } = req.body;
  const userId = req.user._id;

  // Find team by joinCode
  const team = await Team.findOne({ joinCode: joinCode.toUpperCase() })
    .populate('event', 'title date location')
    .populate('members', 'email role');

  if (!team) {
    throw new NotFoundError('Team', `with join code ${joinCode}`);
  }

  // Check if user is registered for the event
  const registration = await Registration.findOne({
    user: userId,
    event: team.event._id
  });

  if (!registration) {
    throw new ConflictError('You must be registered for the event to join a team');
  }

  // Check if team is at full capacity
  if (team.members.length >= team.capacity) {
    throw new ConflictError('Team is at full capacity');
  }

  // Check if user is already in a team for this event
  const existingTeam = await Team.findOne({
    event: team.event._id,
    members: userId
  });

  if (existingTeam) {
    throw new ConflictError('You are already in a team for this event');
  }

  // Add user to team members
  team.members.push(userId);
  await team.save();

  // Populate members for response
  await team.populate('members', 'email role');

  res.status(200).json({
    success: true,
    team
  });
});

/**
 * Get Event Teams
 * GET /api/teams/event/:eventId
 * Protected route (participant or admin)
 * 
 * Validates: Requirements 8.6
 * 
 * Finds all teams for event
 * Populates member info
 * Returns list with memberCount
 */
exports.getEventTeams = asyncHandler(async (req, res, next) => {
  const { eventId } = req.params;

  // Verify event exists
  const event = await Event.findById(eventId);
  if (!event) {
    throw new NotFoundError('Event', eventId);
  }

  // Find all teams for event
  const teams = await Team.find({ event: eventId })
    .populate('members', 'email role')
    .populate('createdBy', 'email role')
    .populate('event', 'title date location')
    .sort({ createdAt: -1 });

  // Add memberCount to each team (virtual field should be included)
  const teamsWithCount = teams.map(team => ({
    ...team.toJSON(),
    memberCount: team.members.length
  }));

  res.status(200).json({
    success: true,
    count: teams.length,
    teams: teamsWithCount
  });
});

/**
 * Delete Team
 * DELETE /api/teams/:id
 * Protected route (admin only)
 * 
 * Validates: Requirements 7.4
 * 
 * Validates admin role (via middleware)
 * Deletes team and all member associations
 * Returns success message
 */
exports.deleteTeam = asyncHandler(async (req, res, next) => {
  const { id } = req.params;

  // Find team
  const team = await Team.findById(id);

  if (!team) {
    throw new NotFoundError('Team', id);
  }

  // Delete team (member associations are removed automatically)
  await Team.findByIdAndDelete(id);

  res.status(200).json({
    success: true,
    message: 'Team deleted successfully'
  });
});

module.exports = exports;
